<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Assuming continent IDs: 1=Africa, 2=Asia, 3=Europe, 4=North America, 5=South America, 6=Oceania
        DB::table('countries')->insert([
            // AFRICA
            ['continent_id' => 1, 'name' => 'Algeria', 'flag' => '🇩🇿'],
            ['continent_id' => 1, 'name' => 'Angola', 'flag' => '🇦🇴'],
            ['continent_id' => 1, 'name' => 'Benin', 'flag' => '🇧🇯'],
            ['continent_id' => 1, 'name' => 'Botswana', 'flag' => '🇧🇼'],
            ['continent_id' => 1, 'name' => 'Burkina Faso', 'flag' => '🇧🇫'],
            ['continent_id' => 1, 'name' => 'Burundi', 'flag' => '🇧🇮'],
            ['continent_id' => 1, 'name' => 'Cameroon', 'flag' => '🇨🇲'],
            ['continent_id' => 1, 'name' => 'Cape Verde', 'flag' => '🇨🇻'],
            ['continent_id' => 1, 'name' => 'Central African Republic', 'flag' => '🇨🇫'],
            ['continent_id' => 1, 'name' => 'Chad', 'flag' => '🇹🇩'],
            ['continent_id' => 1, 'name' => 'Comoros', 'flag' => '🇰🇲'],
            ['continent_id' => 1, 'name' => 'Congo', 'flag' => '🇨🇬'],
            ['continent_id' => 1, 'name' => 'DR Congo', 'flag' => '🇨🇩'],
            ['continent_id' => 1, 'name' => 'Djibouti', 'flag' => '🇩🇯'],
            ['continent_id' => 1, 'name' => 'Egypt', 'flag' => '🇪🇬'],
            ['continent_id' => 1, 'name' => 'Equatorial Guinea', 'flag' => '🇬🇶'],
            ['continent_id' => 1, 'name' => 'Eritrea', 'flag' => '🇪🇷'],
            ['continent_id' => 1, 'name' => 'Eswatini', 'flag' => '🇸🇿'],
            ['continent_id' => 1, 'name' => 'Ethiopia', 'flag' => '🇪🇹'],
            ['continent_id' => 1, 'name' => 'Gabon', 'flag' => '🇬🇦'],
            ['continent_id' => 1, 'name' => 'Gambia', 'flag' => '🇬🇲'],
            ['continent_id' => 1, 'name' => 'Ghana', 'flag' => '🇬🇭'],
            ['continent_id' => 1, 'name' => 'Guinea', 'flag' => '🇬🇳'],
            ['continent_id' => 1, 'name' => 'Guinea-Bissau', 'flag' => '🇬🇼'],
            ['continent_id' => 1, 'name' => 'Ivory Coast', 'flag' => '🇨🇮'],
            ['continent_id' => 1, 'name' => 'Kenya', 'flag' => '🇰🇪'],
            ['continent_id' => 1, 'name' => 'Lesotho', 'flag' => '🇱🇸'],
            ['continent_id' => 1, 'name' => 'Liberia', 'flag' => '🇱🇷'],
            ['continent_id' => 1, 'name' => 'Libya', 'flag' => '🇱🇾'],
            ['continent_id' => 1, 'name' => 'Madagascar', 'flag' => '🇲🇬'],
            ['continent_id' => 1, 'name' => 'Malawi', 'flag' => '🇲🇼'],
            ['continent_id' => 1, 'name' => 'Mali', 'flag' => '🇲🇱'],
            ['continent_id' => 1, 'name' => 'Mauritania', 'flag' => '🇲🇷'],
            ['continent_id' => 1, 'name' => 'Mauritius', 'flag' => '🇲🇺'],
            ['continent_id' => 1, 'name' => 'Morocco', 'flag' => '🇲🇦'],
            ['continent_id' => 1, 'name' => 'Mozambique', 'flag' => '🇲🇿'],
            ['continent_id' => 1, 'name' => 'Namibia', 'flag' => '🇳🇦'],
            ['continent_id' => 1, 'name' => 'Niger', 'flag' => '🇳🇪'],
            ['continent_id' => 1, 'name' => 'Nigeria', 'flag' => '🇳🇬'],
            ['continent_id' => 1, 'name' => 'Rwanda', 'flag' => '🇷🇼'],
            ['continent_id' => 1, 'name' => 'São Tomé and Príncipe', 'flag' => '🇸🇹'],
            ['continent_id' => 1, 'name' => 'Senegal', 'flag' => '🇸🇳'],
            ['continent_id' => 1, 'name' => 'Seychelles', 'flag' => '🇸🇨'],
            ['continent_id' => 1, 'name' => 'Sierra Leone', 'flag' => '🇸🇱'],
            ['continent_id' => 1, 'name' => 'Somalia', 'flag' => '🇸🇴'],
            ['continent_id' => 1, 'name' => 'South Africa', 'flag' => '🇿🇦'],
            ['continent_id' => 1, 'name' => 'South Sudan', 'flag' => '🇸🇸'],
            ['continent_id' => 1, 'name' => 'Sudan', 'flag' => '🇸🇩'],
            ['continent_id' => 1, 'name' => 'Tanzania', 'flag' => '🇹🇿'],
            ['continent_id' => 1, 'name' => 'Togo', 'flag' => '🇹🇬'],
            ['continent_id' => 1, 'name' => 'Tunisia', 'flag' => '🇹🇳'],
            ['continent_id' => 1, 'name' => 'Uganda', 'flag' => '🇺🇬'],
            ['continent_id' => 1, 'name' => 'Zambia', 'flag' => '🇿🇲'],
            ['continent_id' => 1, 'name' => 'Zimbabwe', 'flag' => '🇿🇼'],

            // ASIA
            ['continent_id' => 2, 'name' => 'Afghanistan', 'flag' => '🇦🇫'],
            ['continent_id' => 2, 'name' => 'Bahrain', 'flag' => '🇧🇭'],
            ['continent_id' => 2, 'name' => 'Bangladesh', 'flag' => '🇧🇩'],
            ['continent_id' => 2, 'name' => 'Bhutan', 'flag' => '🇧🇹'],
            ['continent_id' => 2, 'name' => 'Brunei', 'flag' => '🇧🇳'],
            ['continent_id' => 2, 'name' => 'Cambodia', 'flag' => '🇰🇭'],
            ['continent_id' => 2, 'name' => 'China', 'flag' => '🇨🇳'],
            ['continent_id' => 2, 'name' => 'Chinese Taipei', 'flag' => '🇹🇼'],
            ['continent_id' => 2, 'name' => 'Guam', 'flag' => '🇬🇺'],
            ['continent_id' => 2, 'name' => 'Hong Kong', 'flag' => '🇭🇰'],
            ['continent_id' => 2, 'name' => 'India', 'flag' => '🇮🇳'],
            ['continent_id' => 2, 'name' => 'Indonesia', 'flag' => '🇮🇩'],
            ['continent_id' => 2, 'name' => 'Iran', 'flag' => '🇮🇷'],
            ['continent_id' => 2, 'name' => 'Iraq', 'flag' => '🇮🇶'],
            ['continent_id' => 2, 'name' => 'Japan', 'flag' => '🇯🇵'],
            ['continent_id' => 2, 'name' => 'Jordan', 'flag' => '🇯🇴'],
            ['continent_id' => 2, 'name' => 'Kazakhstan', 'flag' => '🇰🇿'],
            ['continent_id' => 2, 'name' => 'Kuwait', 'flag' => '🇰🇼'],
            ['continent_id' => 2, 'name' => 'Kyrgyzstan', 'flag' => '🇰🇬'],
            ['continent_id' => 2, 'name' => 'Laos', 'flag' => '🇱🇦'],
            ['continent_id' => 2, 'name' => 'Lebanon', 'flag' => '🇱🇧'],
            ['continent_id' => 2, 'name' => 'Macau', 'flag' => '🇲🇴'],
            ['continent_id' => 2, 'name' => 'Malaysia', 'flag' => '🇲🇾'],
            ['continent_id' => 2, 'name' => 'Maldives', 'flag' => '🇲🇻'],
            ['continent_id' => 2, 'name' => 'Mongolia', 'flag' => '🇲🇳'],
            ['continent_id' => 2, 'name' => 'Myanmar', 'flag' => '🇲🇲'],
            ['continent_id' => 2, 'name' => 'Nepal', 'flag' => '🇳🇵'],
            ['continent_id' => 2, 'name' => 'North Korea', 'flag' => '🇰🇵'],
            ['continent_id' => 2, 'name' => 'Oman', 'flag' => '🇴🇲'],
            ['continent_id' => 2, 'name' => 'Pakistan', 'flag' => '🇵🇰'],
            ['continent_id' => 2, 'name' => 'Palestine', 'flag' => '🇵🇸'],
            ['continent_id' => 2, 'name' => 'Philippines', 'flag' => '🇵🇭'],
            ['continent_id' => 2, 'name' => 'Qatar', 'flag' => '🇶🇦'],
            ['continent_id' => 2, 'name' => 'Saudi Arabia', 'flag' => '🇸🇦'],
            ['continent_id' => 2, 'name' => 'Singapore', 'flag' => '🇸🇬'],
            ['continent_id' => 2, 'name' => 'South Korea', 'flag' => '🇰🇷'],
            ['continent_id' => 2, 'name' => 'Sri Lanka', 'flag' => '🇱🇰'],
            ['continent_id' => 2, 'name' => 'Syria', 'flag' => '🇸🇾'],
            ['continent_id' => 2, 'name' => 'Tajikistan', 'flag' => '🇹🇯'],
            ['continent_id' => 2, 'name' => 'Thailand', 'flag' => '🇹🇭'],
            ['continent_id' => 2, 'name' => 'Timor-Leste', 'flag' => '🇹🇱'],
            ['continent_id' => 2, 'name' => 'Turkmenistan', 'flag' => '🇹🇲'],
            ['continent_id' => 2, 'name' => 'United Arab Emirates', 'flag' => '🇦🇪'],
            ['continent_id' => 2, 'name' => 'Uzbekistan', 'flag' => '🇺🇿'],
            ['continent_id' => 2, 'name' => 'Vietnam', 'flag' => '🇻🇳'],
            ['continent_id' => 2, 'name' => 'Yemen', 'flag' => '🇾🇪'],

            // EUROPE
            ['continent_id' => 3, 'name' => 'Albania', 'flag' => '🇦🇱'],
            ['continent_id' => 3, 'name' => 'Andorra', 'flag' => '🇦🇩'],
            ['continent_id' => 3, 'name' => 'Armenia', 'flag' => '🇦🇲'],
            ['continent_id' => 3, 'name' => 'Austria', 'flag' => '🇦🇹'],
            ['continent_id' => 3, 'name' => 'Azerbaijan', 'flag' => '🇦🇿'],
            ['continent_id' => 3, 'name' => 'Belarus', 'flag' => '🇧🇾'],
            ['continent_id' => 3, 'name' => 'Belgium', 'flag' => '🇧🇪'],
            ['continent_id' => 3, 'name' => 'Bosnia and Herzegovina', 'flag' => '🇧🇦'],
            ['continent_id' => 3, 'name' => 'Bulgaria', 'flag' => '🇧🇬'],
            ['continent_id' => 3, 'name' => 'Croatia', 'flag' => '🇭🇷'],
            ['continent_id' => 3, 'name' => 'Cyprus', 'flag' => '🇨🇾'],
            ['continent_id' => 3, 'name' => 'Czech Republic', 'flag' => '🇨🇿'],
            ['continent_id' => 3, 'name' => 'Denmark', 'flag' => '🇩🇰'],
            ['continent_id' => 3, 'name' => 'England', 'flag' => '🏴󠁧󠁢󠁥󠁮󠁧󠁿'],
            ['continent_id' => 3, 'name' => 'Estonia', 'flag' => '🇪🇪'],
            ['continent_id' => 3, 'name' => 'Faroe Islands', 'flag' => '🇫🇴'],
            ['continent_id' => 3, 'name' => 'Finland', 'flag' => '🇫🇮'],
            ['continent_id' => 3, 'name' => 'France', 'flag' => '🇫🇷'],
            ['continent_id' => 3, 'name' => 'Georgia', 'flag' => '🇬🇪'],
            ['continent_id' => 3, 'name' => 'Germany', 'flag' => '🇩🇪'],
            ['continent_id' => 3, 'name' => 'Gibraltar', 'flag' => '🇬🇮'],
            ['continent_id' => 3, 'name' => 'Greece', 'flag' => '🇬🇷'],
            ['continent_id' => 3, 'name' => 'Hungary', 'flag' => '🇭🇺'],
            ['continent_id' => 3, 'name' => 'Iceland', 'flag' => '🇮🇸'],
            ['continent_id' => 3, 'name' => 'Ireland', 'flag' => '🇮🇪'],
            ['continent_id' => 3, 'name' => 'Israel', 'flag' => '🇮🇱'],
            ['continent_id' => 3, 'name' => 'Italy', 'flag' => '🇮🇹'],
            ['continent_id' => 3, 'name' => 'Kosovo', 'flag' => '🇽🇰'],
            ['continent_id' => 3, 'name' => 'Latvia', 'flag' => '🇱🇻'],
            ['continent_id' => 3, 'name' => 'Liechtenstein', 'flag' => '🇱🇮'],
            ['continent_id' => 3, 'name' => 'Lithuania', 'flag' => '🇱🇹'],
            ['continent_id' => 3, 'name' => 'Luxembourg', 'flag' => '🇱🇺'],
            ['continent_id' => 3, 'name' => 'Malta', 'flag' => '🇲🇹'],
            ['continent_id' => 3, 'name' => 'Moldova', 'flag' => '🇲🇩'],
            ['continent_id' => 3, 'name' => 'Monaco', 'flag' => '🇲🇨'],
            ['continent_id' => 3, 'name' => 'Montenegro', 'flag' => '🇲🇪'],
            ['continent_id' => 3, 'name' => 'Netherlands', 'flag' => '🇳🇱'],
            ['continent_id' => 3, 'name' => 'North Macedonia', 'flag' => '🇲🇰'],
            ['continent_id' => 3, 'name' => 'Northern Ireland', 'flag' => '🇬🇧'],
            ['continent_id' => 3, 'name' => 'Norway', 'flag' => '🇳🇴'],
            ['continent_id' => 3, 'name' => 'Poland', 'flag' => '🇵🇱'],
            ['continent_id' => 3, 'name' => 'Portugal', 'flag' => '🇵🇹'],
            ['continent_id' => 3, 'name' => 'Romania', 'flag' => '🇷🇴'],
            ['continent_id' => 3, 'name' => 'Russia', 'flag' => '🇷🇺'],
            ['continent_id' => 3, 'name' => 'San Marino', 'flag' => '🇸🇲'],
            ['continent_id' => 3, 'name' => 'Scotland', 'flag' => '🏴󠁧󠁢󠁳󠁣󠁴󠁿'],
            ['continent_id' => 3, 'name' => 'Serbia', 'flag' => '🇷🇸'],
            ['continent_id' => 3, 'name' => 'Slovakia', 'flag' => '🇸🇰'],
            ['continent_id' => 3, 'name' => 'Slovenia', 'flag' => '🇸🇮'],
            ['continent_id' => 3, 'name' => 'Spain', 'flag' => '🇪🇸'],
            ['continent_id' => 3, 'name' => 'Sweden', 'flag' => '🇸🇪'],
            ['continent_id' => 3, 'name' => 'Switzerland', 'flag' => '🇨🇭'],
            ['continent_id' => 3, 'name' => 'Turkey', 'flag' => '🇹🇷'],
            ['continent_id' => 3, 'name' => 'Ukraine', 'flag' => '🇺🇦'],
            ['continent_id' => 3, 'name' => 'Wales', 'flag' => '🏴󠁧󠁢󠁷󠁬󠁳󠁿'],

            // NORTH AMERICA & CENTRAL AMERICA & CARIBBEAN
            ['continent_id' => 4, 'name' => 'Anguilla', 'flag' => '🇦🇮'],
            ['continent_id' => 4, 'name' => 'Antigua and Barbuda', 'flag' => '🇦🇬'],
            ['continent_id' => 4, 'name' => 'Aruba', 'flag' => '🇦🇼'],
            ['continent_id' => 4, 'name' => 'Bahamas', 'flag' => '🇧🇸'],
            ['continent_id' => 4, 'name' => 'Barbados', 'flag' => '🇧🇧'],
            ['continent_id' => 4, 'name' => 'Belize', 'flag' => '🇧🇿'],
            ['continent_id' => 4, 'name' => 'Bermuda', 'flag' => '🇧🇲'],
            ['continent_id' => 4, 'name' => 'British Virgin Islands', 'flag' => '🇻🇬'],
            ['continent_id' => 4, 'name' => 'Canada', 'flag' => '🇨🇦'],
            ['continent_id' => 4, 'name' => 'Cayman Islands', 'flag' => '🇰🇾'],
            ['continent_id' => 4, 'name' => 'Costa Rica', 'flag' => '🇨🇷'],
            ['continent_id' => 4, 'name' => 'Cuba', 'flag' => '🇨🇺'],
            ['continent_id' => 4, 'name' => 'Curaçao', 'flag' => '🇨🇼'],
            ['continent_id' => 4, 'name' => 'Dominica', 'flag' => '🇩🇲'],
            ['continent_id' => 4, 'name' => 'Dominican Republic', 'flag' => '🇩🇴'],
            ['continent_id' => 4, 'name' => 'El Salvador', 'flag' => '🇸🇻'],
            ['continent_id' => 4, 'name' => 'Grenada', 'flag' => '🇬🇩'],
            ['continent_id' => 4, 'name' => 'Guadeloupe', 'flag' => '🇬🇵'],
            ['continent_id' => 4, 'name' => 'Guatemala', 'flag' => '🇬🇹'],
            ['continent_id' => 4, 'name' => 'Guyana', 'flag' => '🇬🇾'],
            ['continent_id' => 4, 'name' => 'Haiti', 'flag' => '🇭🇹'],
            ['continent_id' => 4, 'name' => 'Honduras', 'flag' => '🇭🇳'],
            ['continent_id' => 4, 'name' => 'Jamaica', 'flag' => '🇯🇲'],
            ['continent_id' => 4, 'name' => 'Martinique', 'flag' => '🇲🇶'],
            ['continent_id' => 4, 'name' => 'Mexico', 'flag' => '🇲🇽'],
            ['continent_id' => 4, 'name' => 'Montserrat', 'flag' => '🇲🇸'],
            ['continent_id' => 4, 'name' => 'Nicaragua', 'flag' => '🇳🇮'],
            ['continent_id' => 4, 'name' => 'Panama', 'flag' => '🇵🇦'],
            ['continent_id' => 4, 'name' => 'Puerto Rico', 'flag' => '🇵🇷'],
            ['continent_id' => 4, 'name' => 'Saint Kitts and Nevis', 'flag' => '🇰🇳'],
            ['continent_id' => 4, 'name' => 'Saint Lucia', 'flag' => '🇱🇨'],
            ['continent_id' => 4, 'name' => 'Saint Vincent and the Grenadines', 'flag' => '🇻🇨'],
            ['continent_id' => 4, 'name' => 'Sint Maarten', 'flag' => '🇸🇽'],
            ['continent_id' => 4, 'name' => 'Suriname', 'flag' => '🇸🇷'],
            ['continent_id' => 4, 'name' => 'Trinidad and Tobago', 'flag' => '🇹🇹'],
            ['continent_id' => 4, 'name' => 'Turks and Caicos Islands', 'flag' => '🇹🇨'],
            ['continent_id' => 4, 'name' => 'United States', 'flag' => '🇺🇸'],
            ['continent_id' => 4, 'name' => 'US Virgin Islands', 'flag' => '🇻🇮'],

            // SOUTH AMERICA
            ['continent_id' => 5, 'name' => 'Argentina', 'flag' => '🇦🇷'],
            ['continent_id' => 5, 'name' => 'Bolivia', 'flag' => '🇧🇴'],
            ['continent_id' => 5, 'name' => 'Brazil', 'flag' => '🇧🇷'],
            ['continent_id' => 5, 'name' => 'Chile', 'flag' => '🇨🇱'],
            ['continent_id' => 5, 'name' => 'Colombia', 'flag' => '🇨🇴'],
            ['continent_id' => 5, 'name' => 'Ecuador', 'flag' => '🇪🇨'],
            ['continent_id' => 5, 'name' => 'French Guiana', 'flag' => '🇬🇫'],
            ['continent_id' => 5, 'name' => 'Paraguay', 'flag' => '🇵🇾'],
            ['continent_id' => 5, 'name' => 'Peru', 'flag' => '🇵🇪'],
            ['continent_id' => 5, 'name' => 'Uruguay', 'flag' => '🇺🇾'],
            ['continent_id' => 5, 'name' => 'Venezuela', 'flag' => '🇻🇪'],

            // OCEANIA
            ['continent_id' => 6, 'name' => 'American Samoa', 'flag' => '🇦🇸'],
            ['continent_id' => 6, 'name' => 'Australia', 'flag' => '🇦🇺'],
            ['continent_id' => 6, 'name' => 'Cook Islands', 'flag' => '🇨🇰'],
            ['continent_id' => 6, 'name' => 'Fiji', 'flag' => '🇫🇯'],
            ['continent_id' => 6, 'name' => 'New Caledonia', 'flag' => '🇳🇨'],
            ['continent_id' => 6, 'name' => 'New Zealand', 'flag' => '🇳🇿'],
            ['continent_id' => 6, 'name' => 'Papua New Guinea', 'flag' => '🇵🇬'],
            ['continent_id' => 6, 'name' => 'Samoa', 'flag' => '🇼🇸'],
            ['continent_id' => 6, 'name' => 'Solomon Islands', 'flag' => '🇸🇧'],
            ['continent_id' => 6, 'name' => 'Tahiti', 'flag' => '🇵🇫'],
            ['continent_id' => 6, 'name' => 'Tonga', 'flag' => '🇹🇴'],
            ['continent_id' => 6, 'name' => 'Vanuatu', 'flag' => '🇻🇺'],
        ]);
    }
}
